name: Bug report
description: Something isn't working as expected
title: "bug: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: "Keep it concise: what you did, what happened, what you expected."
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? Include steps to reproduce.
      placeholder: |
        I ran notebook Cell 7 with CITY="Milan" and got:
        ```
        Error: ...
        ```
        
        Expected: ...
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Version, OS, Python version
      placeholder: "v2.3.0, Windows 11, Python 3.12"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / traceback (if applicable)
      render: shell
