#!/usr/bin/env python3
"""
Setup Wizard - Configure Satellite City Analyzer

First-time setup for new users. Creates config.yaml with your preferences.

Usage:
    python scripts/setup.py
"""

import sys
from pathlib import Path


def print_header():
    print()
    print("=" * 60)
    print("  SATELLITE CITY ANALYZER - Setup Wizard")
    print("=" * 60)
    print()


def check_dependencies():
    """Check if all required packages are installed."""
    print("Checking dependencies...")
    
    required = {
        "numpy": "numpy",
        "rasterio": "rasterio", 
        "matplotlib": "matplotlib",
        "scikit-learn": "sklearn",
        "geopy": "geopy",
        "shapely": "shapely",
        "requests": "requests",
        "tqdm": "tqdm",
    }
    
    missing = []
    for name, import_name in required.items():
        try:
            __import__(import_name)
            print(f"   [OK] {name}")
        except ImportError:
            print(f"   [X] {name} - MISSING")
            missing.append(name)
    
    if missing:
        print()
        print("[ERROR] Missing dependencies!")
        print()
        print("   Install with:")
        print("   pip install -e .")
        print()
        print("   Or individually:")
        print(f"   pip install {' '.join(missing)}")
        return False
    
    print()
    print("[OK] All dependencies installed!")
    return True


def setup_copernicus():
    """Setup Copernicus credentials."""
    print()
    print("-" * 60)
    print("Copernicus Data Space Configuration")
    print("-" * 60)
    print()
    print("To download satellite data automatically, you need")
    print("credentials from Copernicus Data Space.")
    print()
    print("Get credentials: https://dataspace.copernicus.eu")
    print("   1. Register/Login")
    print("   2. User Settings > OAuth clients")
    print("   3. Create new client")
    print()
    
    choice = input("Configure Copernicus credentials? (y/N): ").strip().lower()
    
    if choice == "y":
        client_id = input("Client ID: ").strip()
        client_secret = input("Client Secret: ").strip()
        return {"client_id": client_id, "client_secret": client_secret}
    
    print()
    print("Skipping Copernicus setup.")
    print("   You can still use manual download or demo mode.")
    return None


def setup_defaults():
    """Setup default preferences."""
    print()
    print("-" * 60)
    print("Default Preferences")
    print("-" * 60)
    print()
    
    city = input("Default city to analyze [Milan]: ").strip() or "Milan"
    
    radius = input("Default radius in km [15]: ").strip() or "15"
    try:
        radius = float(radius)
    except:
        radius = 15.0
    
    print()
    print("Classification methods:")
    print("  1. consensus - Best accuracy (K-Means + Spectral)")
    print("  2. kmeans    - Fast clustering")
    print("  3. spectral  - Rule-based")
    method = input("Default method [1]: ").strip() or "1"
    methods = {"1": "consensus", "2": "kmeans", "3": "spectral"}
    method = methods.get(method, "consensus")
    
    return {"city": city, "radius_km": radius, "method": method}


def save_config(copernicus_creds, defaults):
    """Save configuration to config.yaml."""
    config_dir = Path("config")
    config_dir.mkdir(exist_ok=True)
    config_path = config_dir / "config.yaml"
    
    lines = [
        "# Satellite City Analyzer Configuration",
        "# Generated by setup.py",
        "",
        "# Copernicus Data Space credentials",
        "# Get yours at: https://dataspace.copernicus.eu",
        "sentinel:",
    ]
    
    if copernicus_creds:
        lines.extend([
            f'  client_id: "{copernicus_creds["client_id"]}"',
            f'  client_secret: "{copernicus_creds["client_secret"]}"',
        ])
    else:
        lines.extend([
            "  client_id: null  # Add your credentials here",
            "  client_secret: null",
        ])
    
    lines.extend([
        "  max_cloud_cover: 20.0",
        "",
        "# Default analysis settings",
        "defaults:",
        f'  city: "{defaults["city"]}"',
        f'  radius_km: {defaults["radius_km"]}',
        f'  method: "{defaults["method"]}"',
        "",
        "# Output settings",
        "output:",
        "  save_preview: true",
        "  save_confidence: true",
        '  format: "png"',
    ])
    
    with open(config_path, "w") as f:
        f.write("\n".join(lines))
    
    return config_path


def main():
    print_header()
    
    if not check_dependencies():
        return 1
    
    copernicus_creds = setup_copernicus()
    defaults = setup_defaults()
    
    print()
    print("-" * 60)
    print("Saving Configuration")
    print("-" * 60)
    config_path = save_config(copernicus_creds, defaults)
    print(f"\n[OK] Config saved to: {config_path}")
    
    print()
    print("=" * 60)
    print("SETUP COMPLETE!")
    print("=" * 60)
    print()
    print("Next steps:")
    print()
    print("  1. Try the demo:")
    print("     python scripts/analyze_city.py --demo")
    print()
    print(f'  2. Analyze {defaults["city"]}:')
    print(f'     python scripts/analyze_city.py --city {defaults["city"]}')
    print()
    if not copernicus_creds:
        print("  To enable auto-download, add Copernicus credentials")
        print("     to config/config.yaml")
        print()
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
